services:
  db_postgres:
    container_name: discount-service-db
    image: postgres:latest
    environment:
      POSTGRES_DB: discountservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - /data